@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

NurseyBook *-down-> "1" UniqueElderlyList
NurseyBook *-right-> "1" UniqueTagList
NurseyBook *-left-> "1" UniqueTaskList
UniqueTagList -[hidden]down- UniqueElderlyList
UniqueTagList -[hidden]down- UniqueElderlyList

UniqueTagList *-right-> "*" Tag
UniqueElderlyList --> Elderly

Elderly -up-|> Person
Nok -up-|> Person
Elderly *-> "*" Tag

Elderly *-left> Nok

@enduml
