@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueElderlyList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueElderlyList
UniqueTagList -[hidden]down- UniqueElderlyList

UniqueTagList *-right-> "*" Tag
UniqueElderlyList --> Person

Elderly -up-|> Person
Nok -up-|> Person
Elderly *-> "*" Tag

Elderly *-left> Nok

@enduml
