@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyNurseyBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class NurseyBook
Class VersionedNurseyBook
Class NurseyBookState
Class ReadOnlyNurseyBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class UniqueElderlyList
Class Elderly

Class UniqueTaskList
Class Task
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

NurseyBook .up..|> ReadOnlyNurseyBook

ModelManager .up..|> Model
Model .right..> ReadOnlyUserPrefs
Model .left..> ReadOnlyNurseyBook
ModelManager -left-> "1" VersionedNurseyBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up..|> ReadOnlyUserPrefs
VersionedNurseyBook -left|> NurseyBook
VersionedNurseyBook -up> "*" NurseyBookState
NurseyBookState -down-> "1" NurseyBook

NurseyBook *--> "1" UniqueElderlyList
UniqueElderlyList --> "~* all" Elderly
NurseyBook *-> "1" UniqueTaskList
UniqueTaskList -> "~* all" Task

'Phone -[hidden]right-> Nursey
'Nursey -[hidden]left-> Email
'Relationship -[hidden]right-> Phone

ModelManager -->"~* filtered" Elderly
ModelManager -->"~* filtered" Task
ModelManager --> "0...1 of interest" Elderly
@enduml
