@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{

package "UserPrefs Storage" #F4F6F6{
Interface UserPrefsStorage <<Interface>>
Class JsonUserPrefsStorage
}

Interface Storage <<Interface>>
Class StorageManager

package "NurseyBook Storage" #F4F6F6{
Interface NurseyBookStorage <<Interface>>
Class JsonNurseyBookStorage
Class JsonSerializableNurseyBook
Class JsonAdaptedElderly
Class JsonAdaptedTask
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" NurseyBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> NurseyBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonNurseyBookStorage .up.|> NurseyBookStorage
JsonNurseyBookStorage ..> JsonSerializableNurseyBook
JsonSerializableNurseyBook --> "*" JsonAdaptedElderly
JsonSerializableNurseyBook --> "*" JsonAdaptedTask
JsonAdaptedElderly --> "*" JsonAdaptedTag

@enduml
