@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NurseyBookParser" as NurseyBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedNurseyBook" as VersionedNurseyBook MODEL_COLOR
end box
[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> NurseyBookParser : parseCommand("undo")
activate NurseyBookParser

create UndoCommand
NurseyBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> NurseyBookParser
deactivate UndoCommand

NurseyBookParser --> LogicManager : u
deactivate NurseyBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoNurseyBook()
activate Model

Model -> VersionedNurseyBook : getCurrentCommandResult()
activate VersionedNurseyBook

VersionedNurseyBook --> Model : commandResult
deactivate VersionedNurseyBook

Model -> VersionedNurseyBook : undo()
activate VersionedNurseyBook

VersionedNurseyBook -> VersionedNurseyBook :resetData(ReadOnlyNurseyBook)
VersionedNurseyBook --> Model :
deactivate VersionedNurseyBook

Model --> UndoCommand : commandResult
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
